// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.VITE_SUPABASE_KEY;

export const supabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
const fallbackUrl = "http://localhost:54321";
const fallbackKey = "public-anon-key";

if (!supabaseConfigured) {
  const missingVars = [
    !SUPABASE_URL ? "VITE_SUPABASE_URL" : null,
    !SUPABASE_PUBLISHABLE_KEY
      ? "VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY / VITE_SUPABASE_KEY)"
      : null,
  ]
    .filter(Boolean)
    .join(", ");

  console.warn(
    `Supabase environment variables are missing: ${missingVars}. Running in offline mode.`
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || fallbackUrl,
  SUPABASE_PUBLISHABLE_KEY || fallbackKey,
  {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
  }
);
