// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrlFromEnv = import.meta.env.VITE_SUPABASE_URL;
const supabaseKeyFromEnv =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.VITE_SUPABASE_KEY;

const SUPABASE_URL = supabaseUrlFromEnv || "http://localhost:54321";
const SUPABASE_PUBLISHABLE_KEY = supabaseKeyFromEnv || "missing-supabase-key";

if (!supabaseUrlFromEnv || !supabaseKeyFromEnv) {
  console.error(
    "Supabase environment variables are missing. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY / VITE_SUPABASE_KEY)."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
